# Generated by Django 4.0.1 on 2022-01-25 22:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TollCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbr', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(12)])),
                ('tag_id', models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(9)])),
                ('license_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1886)])),
                ('tag_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='backend.tollcompany')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StationsList', to='backend.tollcompany')),
            ],
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('charge', models.FloatField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PassesList', to='backend.station')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PassesList', to='backend.vehicle')),
            ],
        ),
    ]
